default: &default
  adapter: sqlite3
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/wedly_development.sqlite3

test:
  <<: *default
  database: db/wedly_test.sqlite3

production:
  <<: *default
  database: db/wedly_production.sqlite3
